@ECHO OFF
::env\Scripts\activate
ECHO -----------------------------------------
ECHO Runing AutoPEP8...
ECHO -----------------------------------------
env\Scripts\autopep8.exe -i -r app.py
env\Scripts\autopep8.exe -i -r setup.py
env\Scripts\autopep8.exe -i -r app\__init__.py
env\Scripts\autopep8.exe -i -r app\controllers\__init__.py
env\Scripts\autopep8.exe -i -r app\controllers\base_controller.py
env\Scripts\autopep8.exe -i -r app\controllers\example_one.py
env\Scripts\autopep8.exe -i -r app\controllers\test.py
env\Scripts\autopep8.exe -i -r app\decorators\__init__.py
env\Scripts\autopep8.exe -i -r app\helpers\__init__.py
env\Scripts\autopep8.exe -i -r app\interfaces\__init__.py
env\Scripts\autopep8.exe -i -r app\interfaces\base_controller.py
env\Scripts\autopep8.exe -i -r app\interfaces\base_model.py
env\Scripts\autopep8.exe -i -r app\interfaces\base_view.py
env\Scripts\autopep8.exe -i -r app\models\__init__.py
env\Scripts\autopep8.exe -i -r app\models\base_model.py
env\Scripts\autopep8.exe -i -r app\models\example_one.py
env\Scripts\autopep8.exe -i -r app\models\entities\__init__.py
env\Scripts\autopep8.exe -i -r app\views\__init__.py
env\Scripts\autopep8.exe -i -r app\views\base_view.py
env\Scripts\autopep8.exe -i -r app\views\example_one.py
env\Scripts\autopep8.exe -i -r pmvcs\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\__main__.py
env\Scripts\autopep8.exe -i -r pmvcs\__version__.py
env\Scripts\autopep8.exe -i -r pmvcs\cli.py
env\Scripts\autopep8.exe -i -r pmvcs\pmvcs.py
env\Scripts\autopep8.exe -i -r pmvcs\core\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\router.py
env\Scripts\autopep8.exe -i -r pmvcs\core\controllers\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\controllers\base_controller.py
env\Scripts\autopep8.exe -i -r pmvcs\core\controllers\menus.py
env\Scripts\autopep8.exe -i -r pmvcs\core\decorators\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\decorators\decorators_views.py
env\Scripts\autopep8.exe -i -r pmvcs\core\helpers\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\helpers\base_helper.py
env\Scripts\autopep8.exe -i -r pmvcs\core\helpers\filters.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\base_controller.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\base_helper.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\base_model.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\base_view.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\menus.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\router.py
env\Scripts\autopep8.exe -i -r pmvcs\core\interfaces\sample.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\about.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\base_model.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\configuration.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\language.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\menus.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\parser.py
env\Scripts\autopep8.exe -i -r pmvcs\core\models\entities\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_config_file.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_defaults.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_example.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_extras.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_files.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_install.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_menus.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_multiple.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_parser.py
env\Scripts\autopep8.exe -i -r pmvcs\core\setup\setup_unique.py
env\Scripts\autopep8.exe -i -r pmvcs\core\views\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\core\views\base_view.py
env\Scripts\autopep8.exe -i -r pmvcs\core\views\sample.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\app.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\controllers\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\controllers\base_controller.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\decorators\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\helpers\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\interfaces\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\interfaces\base_controller.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\interfaces\base_model.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\interfaces\base_view.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\models\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\models\base_model.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\models\entities\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\views\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\defaults\views\base_view.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\example\controllers\base_controller.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\example\controllers\example_one.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\example\models\example_one.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\example\views\example_one.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\module_unique\controllers\unique.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\modules_base\controllers\controller.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\modules_base\models\model.py
env\Scripts\autopep8.exe -i -r pmvcs\setup\modules_base\views\view.py
env\Scripts\autopep8.exe -i -r pmvcs\tests\__init__.py
env\Scripts\autopep8.exe -i -r pmvcs\tests\test_default.py
pause